# Generated by Django 4.1 on 2022-08-18 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField()),
                ('race_name', models.CharField(max_length=200)),
                ('distance_km', models.FloatField()),
                ('course', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RaceCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=1)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racereport.race')),
            ],
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racer_name', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=200)),
                ('position', models.IntegerField()),
                ('time_ms', models.IntegerField()),
                ('gap_to_first_ms', models.IntegerField()),
                ('zp_rank_before', models.FloatField()),
                ('zp_rank_event', models.FloatField()),
                ('race_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racereport.racecat')),
            ],
        ),
    ]
