# Generated by Django 4.1 on 2022-08-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racereport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='event_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
