# Generated by Django 4.1 on 2022-08-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racereport', '0003_rename_race_name_race_event_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='event_time',
            new_name='event_datetime',
        ),
    ]
