# Generated by Django 4.1 on 2022-08-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racereport', '0004_rename_event_time_race_event_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='course',
        ),
        migrations.RemoveField(
            model_name='race',
            name='distance_km',
        ),
    ]
