# Generated by Django 4.1 on 2022-08-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racereport', '0005_remove_race_course_remove_race_distance_km'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceresult',
            name='gap_to_first_ms',
        ),
    ]
