# Generated by Django 4.1 on 2022-09-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racereport', '0007_team_alter_raceresult_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrape_start', models.DateTimeField()),
                ('scrape_end', models.DateTimeField()),
                ('completed', models.BooleanField()),
                ('count_successful', models.IntegerField()),
            ],
        ),
    ]
