# Generated by Django 4.1 on 2022-09-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racereport', '0010_narrative'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrative',
            name='combined_score',
            field=models.IntegerField(default=0),
        ),
    ]
