# Generated by Django 4.1 on 2022-09-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racereport', '0011_narrative_combined_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='racecat',
            name='include',
            field=models.BooleanField(default=True),
        ),
    ]
