# Generated by Django 4.1 on 2022-09-21 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racereport', '0012_racecat_include'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zp_url', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=1)),
                ('stream_url', models.CharField(max_length=200)),
                ('streamer', models.CharField(max_length=200)),
                ('commentary', models.BooleanField(default=False)),
                ('upvotes', models.IntegerField(default=0)),
                ('race_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racereport.racecat')),
            ],
        ),
    ]
