# Generated by Django 4.1 on 2022-09-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racereport', '0013_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='racecat',
            name='has_video',
            field=models.BooleanField(default=False),
        ),
    ]
