# Generated by Django 4.1 on 2022-09-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racereport', '0014_racecat_has_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
