# Generated by Django 4.1 on 2022-09-24 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racereport', '0015_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='race',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='racereport.race'),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(default='auto_created', max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='video',
            name='race_cat',
        ),
        migrations.AlterField(
            model_name='video',
            name='streamer',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='race_cat',
            field=models.ManyToManyField(to='racereport.racecat'),
        ),
    ]
