# Generated by Django 4.1 on 2022-10-05 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racereport', '0016_video_race_video_status_video_thumbnail_video_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_category', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('streamer_name', models.CharField(max_length=200)),
                ('youtube_url', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('zwiftpower_url', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('zwiftpower_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='streamer_object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='racereport.streamer'),
        ),
    ]
