# Generated by Django 4.1 on 2022-10-05 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racereport', '0017_streamer_video_streamer_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamer',
            old_name='youtube_url',
            new_name='youtube_channel_id',
        ),
    ]
